name: pengeluaranku
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Icon iOS style
  cupertino_icons: ^1.0.8

  # Gunakan Riverpod versi stabil 2.5.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Jika nanti kamu ingin menambah gambar, tinggal aktifkan baris berikut:
  # assets:
  #   - assets/images/
